language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

script:
  - npm run test

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: upload
    skip_cleanup: true
    on:
      repo: georgiah/app-playground
    bucket: app-playground-storage
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: app-playground-storage
    key: latest.zip
    bundle_type: zip
    application: app-playground
    deployment_group: playground
    region: ap-southeast-2
    on:
      repo: georgiah/app-playground

script:
  - zip -r latest * -x node_modules/\*
  - mkdir -p upload
  - mv latest.zip upload/latest.zip
