version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/app-playground
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
hooks:
  AfterInstall:
    - location: deploy_hooks/hook-afterinstall.sh
  ApplicationStart:
    - location: deploy_hooks/hook-applicationstart.sh
